set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property PACKAGE_PIN U17 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN G19 [get_ports {vga_red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_red[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_blu[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blu[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_blu[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blu[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_blu[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blu[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_blu[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_blu[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_grn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_grn[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_grn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_grn[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_grn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_grn[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_grn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_grn[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
